# version: '3'
# services:
#   hologram:
#     build: ./
#     container_name: hologram_interface
#     ports:
#       - 3001:3000
#     networks:
#       - db_network
#     environment:
#       - CHOKIDAR_USEPOLLING=true

# networks:
#   db_network:


version: '3.7'

services:
  hologram:
    build: ./
    container_name: hologram_interface
    restart: always
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    external:
      name: db_network


